service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  role: arn:aws:iam::322598643824:role/Github-OIDC-Lambda
  deploymentBucket: basic-serverless-lambda-p-serverlessdeploymentbuck-a3eimrpt50lb

functions:
  hello:
    handler: controllers/randomNumberController.handle
    events:
      - http:
          path: generate
          method: get
