service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  role: arn:aws:iam::322598643824:role/Github-OIDC-Lambda

functions:
  hello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
